### ISSUE TITLE
无论是在线的链接或是下载的字体的.ttf和.woff都无法解析，使用字体工具提示字体破损

### ISSUE THREAD

**Issue by feinimouse** [thx/iconfont-plus#1019]
笔者首先在我的项目中，点击下载至本地，得到了iconfont demo的压缩包

运行压缩包中的html demo，但仅有基于svg的demo_symbol.html可以正确显示

基于fontclass和unicode的demo都无法正确运行，chrome浏览器提示`Failed to decode downloaded font`

笔者又将下载的.ttf和.woff字体用专用字体解析工具进行解析，提示字体已破损。

之后笔者又尝试复制iconfont，我的项目，中生成的在线Unicode的字体样式：

```css
@font-face {
  font-family: 'iconfont';  /* project id 852442 */
  src: url('//at.alicdn.com/t/font_852442_qjeaw9li2ha.eot');
  src: url('//at.alicdn.com/t/font_852442_qjeaw9li2ha.eot?#iefix') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_852442_qjeaw9li2ha.woff') format('woff'),
  url('//at.alicdn.com/t/font_852442_qjeaw9li2ha.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_852442_qjeaw9li2ha.svg#iconfont') format('svg');
}
```

很遗憾chrome浏览器和字体工具还是提示无法解析

最后笔者又尝试了css在线链接：`//at.alicdn.com/t/font_852442_qjeaw9li2ha.css`

很遗憾还是无法解析

望iconfont项目组能给予解决方案
