### ISSUE TITLE
bug 如果将项目中不需要的字体删除后，然后上传svg到库中，添加到项目，那么新上传的字体会和删除的字体同编号，导致新上传的字体失效

### ISSUE THREAD

**Issue by 1015770492** [thx/iconfont-plus#1785]
使用的时unicode方式使用

通过在线生成字体
然后再需要使用的地方引用在线地址
```css
@font-face {
  font-family: 'iconfont';  /* project id 2045485 */
  src: url('//at.alicdn.com/t/font_2045485_dftt1bv2j54.eot');
  src: url('//at.alicdn.com/t/font_2045485_dftt1bv2j54.eot?#iefix') format('embedded-opentype'),
      url('//at.alicdn.com/t/font_2045485_dftt1bv2j54.woff2') format('woff2'),
      url('//at.alicdn.com/t/font_2045485_dftt1bv2j54.woff') format('woff'),
      url('//at.alicdn.com/t/font_2045485_dftt1bv2j54.ttf') format('truetype'),
      url('//at.alicdn.com/t/font_2045485_dftt1bv2j54.svg#iconfont') format('svg');
}

.iconfont
  font-family: "iconfont" !important;
  font-style: normal;
  line-height 40px
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 0.2px;
  -moz-osx-font-smoothing: grayscale;

/*标签*/
<i class="iconfont">&#xe600;</i>
```

![image](https://user-images.githubusercontent.com/43501801/97697977-c41b8100-1ae2-11eb-80a0-3effe2531e72.png)
