### ISSUE TITLE
.iconfont font-size 建议改成 inherit

### ISSUE THREAD

**Issue by belerweb** [thx/iconfont-plus#363]
图标最常用语按钮等装饰场景，更多的情况希望icon的大小继承父级容器的字体大小。

**Comment by justinyueh** [comment]
同意楼上的建议，否则每次改大小都要这样写，很费事
```css
.xxx .iconfont {
  font-size: 12px;
}
```
