### ISSUE TITLE
Font class 是否可以提供 less 文件

### ISSUE THREAD

**Issue by nimojs** [thx/iconfont-plus#390]
虽然直接将  http://at.alicdn.com/t/font_0ti2e53qo6gbke29.css 复制到本地，并修改文件后缀为 less 就可以在 less 中用了。

但是有时候需要的是
```css
.icon-check:after { content: "\e645"; }
```
所以目前我是在下载到本地后自己运行脚本编译一遍

```js
var fs = require('fs')
var path = require('path')
var filepath = path.join(__dirname, '../m/icons/index.less')

var css = fs.readFileSync(filepath, 'utf-8').toString()
var lessSource = css.replace(/\.icon-(.*):before\s*{\s*content:\s*"([^"]+)";\s*}/g, [
    '.icon-$1(){&:before { content: "$2"; .iconfont;}}',
    '.icon-$1A(){&:after { content: "$2"; .iconfont;}}',
    '@icon-$1: "$2";'
    ].join('\n'))
    .replace(/\.iconfont/g, '.iconfont()')
    .replace(/font-size:16px;/g, '')
    .replace(/\?t=\d*(#[^']+)?/g,'')
    .replace(/url\(\'iconfont/g, "url('./iconfont")
console.log('------ less ---------')
console.log(lessSource)
console.log('------ less ---------')
var dest = path.join(filepath)
fs.writeFileSync(dest, lessSource, 'utf-8')
console.log(dest + ' writeFile done!')
```

**原文件**
```css

@font-face {font-family: "iconfont";
  src: url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.eot?t=1489469451528'); /* IE9*/
  src: url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.eot?t=1489469451528#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.woff?t=1489469451528') format('woff'), /* chrome, firefox */
  url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.ttf?t=1489469451528') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.svg?t=1489469451528#iconfont') format('svg'); /* iOS 4.1- */
}

.iconfont {
  font-family:"iconfont" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-check:before { content: "\e645"; }

.icon-close:before { content: "\e646"; }

```

编译后的文件
```less

@font-face {font-family: "iconfont";
  src: url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.eot'); /* IE9*/
  src: url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.eot') format('embedded-opentype'), /* IE6-IE8 */
  url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.woff') format('woff'), /* chrome, firefox */
  url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.ttf') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('//at.alicdn.com/t/font_0ti2e53qo6gbke29.svg') format('svg'); /* iOS 4.1- */
}

.iconfont() {
  font-family:"iconfont" !important;

  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-check(){&:before { content: "\e645"; .iconfont();}}
.icon-checkA(){&:after { content: "\e645"; .iconfont();}}
@icon-check: "\e645";

.icon-close(){&:before { content: "\e646"; .iconfont();}}
.icon-closeA(){&:after { content: "\e646"; .iconfont();}}
@icon-close: "\e646";

```
