### ISSUE TITLE
微信浏览器不显示iconfont

### ISSUE THREAD

**Issue by Yixifan** [thx/iconfont-plus#478]
在手机微信浏览器上，不显示iconfont字体图标。其他浏览器显示都正常，请大神帮忙一下。

**Comment by muyea** [comment]
```css
@font-face {font-family: "iconfont";
  src: url('iconfont.eot'); /* IE9*/
  src: url('iconfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('iconfont.woff') format('woff'), /* chrome、firefox */
  url('iconfont.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url('iconfont.svg#iconfont') format('svg'); /* iOS 4.1- */
}
```
解决方案：去掉svg后面的format('svg')
```css
@font-face {font-family: "iconfont";
  src: url('iconfont.eot'); /* IE9*/
  src: url('iconfont.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('iconfont.woff') format('woff'), /* chrome、firefox */
  url('iconfont.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url('iconfont.svg#iconfont'); /* iOS 4.1- */
}
```
[具体问题分析参考这里](https://meicj.com/post/iconfont-compatible-issue-on-android.html#end)
