### ISSUE TITLE
文字渲染效果不佳

### ISSUE THREAD

**Issue by fishpaw** [thx/iconfont-plus#63]
网站中的字体在非 Retina 显示屏下的显示效果不是很好，一般而言，14px 字体在这种情况下的显示应该是中规中矩的，不至于特别虚。
而且我有注意到 font-family 的指定也是有些离奇：tahoma,"microsoft yahei"，不知是出于什么考虑？

**Comment by fishpaw** [comment]
在首页的 header 和 footer，这个问题尤其严重， footer 已经基本上上看不清楚内容了。
![image](https://cloud.githubusercontent.com/assets/18455040/19794071/4654214e-9d02-11e6-93d0-8d5c3d2dbbf1.png)

**Comment by yisibl** [comment]
好的，我们会去掉全局的，应该就可以了，和 font-family 设定没有关系。

```css
body {
  -webkit-font-smoothing: antialiased;
}
```
